services:
  mysql:
    container_name: kapoot-mysql-dev
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: kapoot
      MYSQL_USER: kapoot
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}
    volumes:
      - mysql-data-dev:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: kapoot-api-dev
    build:
      context: ./backend
      dockerfile: ./docker/dev/Dockerfile
      args:
        UID: ${UID:?}
        GID: ${GID:?}
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_CLI_HOME: "/tmp/.dotnet"
      ConnectionStrings__DefaultConnection: Server=mysql;Database=kapoot;User=kapoot;Password=${MYSQL_PASSWORD:?};
    user: ${UID:?}:${GID:?}
    volumes:
      - ./backend:/app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${DOCKER_API_PORT:-5000}:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/dev/Dockerfile
    container_name: kapoot-frontend-dev
    depends_on:
      - api
    ports:
      - "${DOCKER_FRONTEND_PORT:-8080}:80"

volumes:
  mysql-data-dev:
