# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/Kernel.php'

    # Ports (interfaces) -> Infrastructure implementations
    App\Application\Repository\UserRepositoryInterface: '@App\Infrastructure\Doctrine\Repository\UserRepository'
    App\Application\Repository\QuizRepositoryInterface: '@App\Infrastructure\Doctrine\Repository\QuizRepository'
    App\Application\Repository\GameSessionRepositoryInterface: '@App\Infrastructure\Doctrine\Repository\GameSessionRepository'
    App\Application\Repository\PlayerRepositoryInterface: '@App\Infrastructure\Doctrine\Repository\PlayerRepository'
    App\Application\Repository\QuestionRepositoryInterface: '@App\Infrastructure\Doctrine\Repository\QuestionRepository'
    App\Application\Repository\ChoiceRepositoryInterface: '@App\Infrastructure\Doctrine\Repository\ChoiceRepository'
    App\Application\Repository\AnswerRepositoryInterface: '@App\Infrastructure\Doctrine\Repository\AnswerRepository'
    App\Application\Repository\ScoreRepositoryInterface: '@App\Infrastructure\Doctrine\Repository\ScoreRepository'
